export enum ErrorCode {
  // Authentication & Authorization Errors
  ERR_USER_EXISTS = 'ERR_USER_EXISTS',
  ERR_INVALID_CREDENTIALS = 'ERR_INVALID_CREDENTIALS',
  ERR_INVALID_REFRESH_TOKEN = 'ERR_INVALID_REFRESH_TOKEN',
  ERR_UNAUTHORIZED = 'ERR_UNAUTHORIZED',
  ERR_FORBIDDEN = 'ERR_FORBIDDEN',

  // Order Domain Errors
  ERR_ORDER_NOT_FOUND = 'ERR_ORDER_NOT_FOUND',
  ERR_INVALID_TRANSITION = 'ERR_INVALID_TRANSITION',
  ERR_POD_ALREADY_DELIVERED = 'ERR_POD_ALREADY_DELIVERED',
  ERR_POD_SIGNATURE_REQUIRED = 'ERR_POD_SIGNATURE_REQUIRED',
  ERR_POD_PHOTO_REQUIRED = 'ERR_POD_PHOTO_REQUIRED',

  // Courier & Dispatch Errors
  ERR_COURIER_NOT_FOUND = 'ERR_COURIER_NOT_FOUND',
  ERR_COURIER_UNAVAILABLE = 'ERR_COURIER_UNAVAILABLE',
  ERR_COURIER_CAPACITY_EXCEEDED = 'ERR_COURIER_CAPACITY_EXCEEDED',

  // Webhook Errors
  ERR_WEBHOOK_NOT_FOUND = 'ERR_WEBHOOK_NOT_FOUND',
  ERR_WEBHOOK_ACCESS_DENIED = 'ERR_WEBHOOK_ACCESS_DENIED',
  ERR_WEBHOOK_DELIVERY_FAILED = 'ERR_WEBHOOK_DELIVERY_FAILED',

  // Storage & Generic System Errors
  ERR_STORAGE_UNAVAILABLE = 'ERR_STORAGE_UNAVAILABLE',
  ERR_BAD_REQUEST = 'ERR_BAD_REQUEST',
  ERR_INTERNAL_SERVER_ERROR = 'ERR_INTERNAL_SERVER_ERROR',
}
